// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp5sSaa-Cy6FBO65VOSqai1EhR2VcXlKE',
    appId: '1:659752238939:android:d2be2f03290e379eb6647e',
    messagingSenderId: '659752238939',
    projectId: 'financial-manage-app-project',
    storageBucket: 'financial-manage-app-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbPbp90oBuqAZM-lKoxgRs3kLYXjOvTOE',
    appId: '1:659752238939:ios:0b10fda990540659b6647e',
    messagingSenderId: '659752238939',
    projectId: 'financial-manage-app-project',
    storageBucket: 'financial-manage-app-project.firebasestorage.app',
    iosBundleId: 'com.sourpringles.financialmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp3G9j11JsDpc4WUDnA4kj4hVLqo-5kHA',
    appId: '1:659752238939:web:baa453cd9284893db6647e',
    messagingSenderId: '659752238939',
    projectId: 'financial-manage-app-project',
    authDomain: 'financial-manage-app-project.firebaseapp.com',
    storageBucket: 'financial-manage-app-project.firebasestorage.app',
    measurementId: 'G-WVL42RSPVZ',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp3G9j11JsDpc4WUDnA4kj4hVLqo-5kHA',
    appId: '1:659752238939:web:a62d1318f61e9c57b6647e',
    messagingSenderId: '659752238939',
    projectId: 'financial-manage-app-project',
    authDomain: 'financial-manage-app-project.firebaseapp.com',
    storageBucket: 'financial-manage-app-project.firebasestorage.app',
    measurementId: 'G-K1JYCDK9DK',
  );

}