// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSGMpK7D7qnzG3XFPvnAIQQzZzDUv3aeE',
    appId: '1:659752238939:web:b641c05992e78d43b6647e',
    messagingSenderId: '659752238939',
    projectId: 'financial-manage-app-project',
    authDomain: 'financial-manage-app-project.firebaseapp.com',
    storageBucket: 'financial-manage-app-project.firebasestorage.app',
    measurementId: 'G-4MBTX406ZC',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSGMpK7D7qnzG3XFPvnAIQQzZzDUv3aeE',
    appId: '1:659752238939:web:5b55a452e940c3b7b6647e',
    messagingSenderId: '659752238939',
    projectId: 'financial-manage-app-project',
    authDomain: 'financial-manage-app-project.firebaseapp.com',
    storageBucket: 'financial-manage-app-project.firebasestorage.app',
    measurementId: 'G-3FW2GTKHVJ',
  );
}
